/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rmoiazcuyxqstijjkauq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtb2lhemN1eXhxc3RpamprYXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTQ5NjksImV4cCI6MjA2ODY3MDk2OX0.zoX7Fzw19NxMdcAwJUJnYMHVaOtwmle9eBzrcZIhY1U"

// Construct Supabase URL from project ID
export const supabaseUrl = `https://${projectId}.supabase.co`

// Check if Supabase is properly configured
export const isSupabaseConfigured = !!(projectId && publicAnonKey && projectId !== 'your-project-id')